version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
      
    working_directory: /go/src/github.com/dpetzold/kube-top
    steps:
      - checkout
      - run: curl https://glide.sh/get | sh
      - run: make build
      - run: go test -v ./...
